[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"

[dependencies]
regex = "1.11.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmarks"
harness = false